import tkinter as tk
from tkinter import messagebox, filedialog
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas as pdf_canvas

from reportlab.lib import colors
import os

def generate_pdf():
    name = entry_name.get()
    title = entry_title.get()
    email = entry_email.get()
    phone = entry_phone.get()
    linkedin = entry_linkedin.get()
    objective = entry_objective.get("1.0", tk.END).strip()
    education = entry_education.get("1.0", tk.END).strip()
    skills = entry_skills.get("1.0", tk.END).strip()
    projects = entry_projects.get("1.0", tk.END).strip()
    achievements = entry_achievements.get("1.0", tk.END).strip()
    color_choice = color_var.get()

    if not name or not email or not phone:
        messagebox.showerror("Error", "Please fill all required fields!")
        return

    file_name = filedialog.asksaveasfilename(
        defaultextension=".pdf",
        filetypes=[("PDF files", "*.pdf")],
        initialfile=name.replace(" ", "_") + "_Resume.pdf"
    )
    if not file_name:
        return

    color_map = {
        "Blue": colors.HexColor("#4193C9"),
        "Teal": colors.HexColor("#008080"),
        "Gray": colors.HexColor("#444444"),
        "Gold": colors.HexColor("#DAA520")
    }
    theme_color = color_map.get(color_choice, colors.black)

    c = pdf_canvas.Canvas(file_name, pagesize=letter)

    width, height = letter

    # Header section with color band
    c.setFillColor(theme_color)
    c.rect(0, height - 90, width, 90, fill=1, stroke=0)

    # Name and Title
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 55, name)
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 75, title)

    # Contact Info
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 50, height - 55, f"Email: {email}")
    c.drawRightString(width - 50, height - 70, f"Phone: {phone}")
    if linkedin:
        c.drawRightString(width - 50, height - 85, f"LinkedIn: {linkedin}")

    y = height - 130

    # Helper function to draw sections
    def section(title, content):
        nonlocal y
        if not content.strip():
            return
        c.setFillColor(theme_color)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, title)
        y -= 15
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 11)
        text = c.beginText(70, y)
        for line in content.split("\n"):
            if line.strip():
                text.textLine("• " + line.strip())
                y -= 14
        c.drawText(text)
        y -= 15

    # Objective (paragraph style)
    if objective:
        c.setFillColor(theme_color)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Objective")
        y -= 18
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 11)
        text = c.beginText(70, y)
        text.textLines(objective)
        c.drawText(text)
        y -= (14 * (objective.count('\n') + 2))

    # Other Sections
    section("Education", education)
    section("Skills", skills)
    section("Projects", projects)
    section("Achievements", achievements)

    # Footer
    c.setStrokeColor(theme_color)
    c.line(50, 50, width - 50, 50)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 35, "Generated by Resume Builder Pro | Built with Python ❤️")

    c.save()
    messagebox.showinfo("Success", f"Professional Resume generated:\n{file_name}")

# ===== Scrollable Tkinter Window =====

root = tk.Tk()
root.title("Stylish Resume Builder")

canvas_frame = tk.Canvas(root, bg="#f9f9f9")
scrollbar = tk.Scrollbar(root, orient="vertical", command=canvas_frame.yview)
scrollable_frame = tk.Frame(canvas_frame, bg="#f9f9f9")

scrollable_frame.bind(
    "<Configure>",
    lambda e: canvas_frame.configure(scrollregion=canvas_frame.bbox("all"))
)

canvas_frame.create_window((0, 0), window=scrollable_frame, anchor="nw")
canvas_frame.configure(yscrollcommand=scrollbar.set)

canvas_frame.pack(side="left", fill="both", expand=True)
scrollbar.pack(side="right", fill="y")

root = scrollable_frame  # so the rest of your code adds widgets to this frame


# Create canvas + scrollbar
main_frame = tk.Frame(root)
main_frame.pack(fill=tk.BOTH, expand=1)

canvas = tk.Canvas(main_frame, bg="#f9f9f9", highlightthickness=0)
canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=1)

scrollbar = tk.Scrollbar(main_frame, orient=tk.VERTICAL, command=canvas.yview)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

canvas.configure(yscrollcommand=scrollbar.set)
canvas.bind('<Configure>', lambda e: canvas.configure(scrollregion=canvas.bbox("all")))

# Create inner frame inside canvas
form_frame = tk.Frame(canvas, bg="#f9f9f9")
canvas.create_window((0, 0), window=form_frame, anchor="nw")

# ===== Form UI =====
def label(text):
    tk.Label(form_frame, text=text, bg="#f9f9f9", font=("Arial", 10, "bold")).pack(anchor="w", padx=20, pady=2)

def textbox(height=3):
    box = tk.Text(form_frame, height=height, width=70)
    box.pack(pady=3)
    return box

label("Full Name *")
entry_name = tk.Entry(form_frame, width=70); entry_name.pack()

label("Job Title (e.g., Software Engineer)")
entry_title = tk.Entry(form_frame, width=70); entry_title.pack()

label("Email *")
entry_email = tk.Entry(form_frame, width=70); entry_email.pack()

label("Phone *")
entry_phone = tk.Entry(form_frame, width=70); entry_phone.pack()

label("LinkedIn (optional)")
entry_linkedin = tk.Entry(form_frame, width=70); entry_linkedin.pack()

label("Objective")
entry_objective = textbox(4)

label("Education")
entry_education = textbox(4)

label("Skills (each skill in new line)")
entry_skills = textbox(4)

label("Projects")
entry_projects = textbox(4)

label("Achievements")
entry_achievements = textbox(4)

label("Choose Template Theme")
color_var = tk.StringVar(value="Blue")
tk.OptionMenu(form_frame, color_var, "Blue", "Teal", "Gray", "Gold").pack(pady=5)

tk.Button(form_frame, text="Generate Professional Resume", bg="#56A7DD", fg="white",
          font=("Arial", 12, "bold"), command=generate_pdf).pack(pady=20)

# Allow mousewheel scrolling
def _on_mousewheel(event):
    canvas.yview_scroll(int(-1*(event.delta/120)), "units")

canvas.bind_all("<MouseWheel>", _on_mousewheel)

root.mainloop()
